# Generated by Django 4.0.1 on 2022-02-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=30)),
                ('password', models.CharField(default='', max_length=30)),
                ('first_name', models.CharField(default='', max_length=30)),
                ('last_name', models.CharField(default='', max_length=30)),
                ('mobile_no', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(default='', max_length=30)),
                ('author1', models.CharField(default='', max_length=30)),
                ('author2', models.CharField(default='', max_length=30)),
                ('author3', models.CharField(default='', max_length=30)),
                ('book_id', models.CharField(default='', max_length=30)),
                ('Availability', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='client_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=30)),
                ('password', models.CharField(default='', max_length=30)),
                ('first_name', models.CharField(default='', max_length=30)),
                ('last_name', models.CharField(default='', max_length=30)),
                ('mis', models.CharField(default='', max_length=30)),
                ('branch', models.CharField(default='', max_length=30)),
                ('college_email', models.CharField(default='', max_length=30)),
                ('mobile_no', models.CharField(default='', max_length=30)),
                ('book1_id', models.CharField(default='', max_length=30)),
                ('date_of_issue1', models.CharField(default='', max_length=30)),
                ('date_of_return1', models.CharField(default='', max_length=30)),
                ('book2_id', models.CharField(default='', max_length=30)),
                ('date_of_issue2', models.CharField(default='', max_length=30)),
                ('date_of_return2', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
